language: node_js
node_js:
- node
- lts/*
- 14
- 12
- 10
os:
- linux
matrix:
  fast_finish: true
cache: yarn
env:
  global:
  - secure: GafZaP9uxJGukTI9UiKlMG5KbrJsin3xn3cRLXVjLLG4ctdPkXY+1w6RPJcRUm0ogCJS95p4HosltayyOQkb1Icve2nuaP4dqi79HKu+OgXqJ2VdNNT1XhK++QThmPrjq11sWank2m7LkbYm+rMj7PzxKUePAmloQUZLypSOQJk7jkQ5KAf0+nQv6K6Oj3xWJyDPFQkokQPc7EreaEV0iKi6RKoOhCed+Ju8KpbzBkj6ksRGwOaEVIkxFn7vNpQPO3X7JXQ/ZNQIB7Pbvolqi6JPuS3s/nnsFTA1Qiv4oQSV90yswH8ZlEZMN2hk8q/S7HzTMPXpZ/GGRNzBThbU+AUyCCiwQ8WzMwS5G0Ks+ICvhYdBc/stVvBpmYq7tQkib2Nj59hjG06AD9D+ZjU3QsmulBQ8jlZaD0zA334y+isQ35LLl6wkfIIzVQIU/dWj8V8x1clKjmhywDPMrTCgimQ9GT+Lk9BHAH0PbmOFQQc+h3ANfrZrypxHX8hhZxC7WxOto4ZGsFcf9nSikVSz9hgVxPlA3+Mkg220zBZEUe/MiBx9Q4ZdL465/NsTmqw6eRkcu28W0BAEVFh3+2GHDAHj4onW2f9PjX/Bdh3s6kXy8NzEFbbPr9wt5HK70x6U9H2rUbPpA2PIyp5UitnihGXXKC4ES1js/IHW0TjV9O4=
install: yarn install --ignore-engines
script: ./scripts/build.sh
after_success:
- cat artifacts/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
